version: "3.8"
services:
   localstack:
     image: localstack/localstack-full:latest
     container_name: localstack
     ports:
       - "127.0.0.1:4510-4559:4510-4559"  
       - "127.0.0.1:4566:4566"            
     networks:
       - "local" 
     environment:
       - AWS_DEFAULT_REGION=eu-central-1
       - DEBUG=${DEBUG-} 
       - DOCKER_HOST=unix:///var/run/docker.sock  
     volumes:
       - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack" 
       - "/var/run/docker.sock:/var/run/docker.sock" 
volumes:
  localstack-data:
    name: localstack-data
networks:
  local:
    driver: bridge
